// packages/react/src/SeasonPicker.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from 'react';
import {
  SeasonPicker as CoreSeasonPicker,
  type SeasonAvailability,
  type SeasonCheckoutHandoff,
  type SeasonDescriptor,
  type SeasonPickerOptions,
  type SeasonRenewalIntent,
} from '@seatlayer/js';

export type {
  SeasonAvailability,
  SeasonCheckoutHandoff,
  SeasonDescriptor,
  SeasonOperation,
  SeasonOperationState,
  SeasonOfferPresentation,
  SeasonPickerOptions,
  SeasonRenewalIntent,
  SeasonStatusEvent,
} from '@seatlayer/js';

/** Imperative controls for the fixed-inclusion Season buyer flow. */
export interface SeasonPickerHandle {
  holdSameSeat(labels: readonly string[], operationId: string): Promise<SeasonCheckoutHandoff>;
  restoreOperation(operationId: string): Promise<SeasonCheckoutHandoff | null>;
  release(releaseActionId: string): Promise<void>;
  createRenewalIntent(offerId: string): Promise<SeasonRenewalIntent>;
  getDescriptor(): SeasonDescriptor | null;
  getAvailability(): SeasonAvailability | null;
  getHandoff(): SeasonCheckoutHandoff | null;
}

/** Props accepted by the React Season wrapper. */
export interface SeasonPickerProps extends Omit<SeasonPickerOptions, 'container'> {
  className?: string;
  style?: CSSProperties;
}

/**
 * React lifecycle adapter for the distinct fixed-inclusion `SeasonPicker`.
 * It never receives a secret key and never turns a browser handoff into proof
 * of price, payment, booking, or renewal.
 */
export const SeasonPicker = forwardRef<SeasonPickerHandle, SeasonPickerProps>(
  function SeasonPicker(props, ref) {
    const {
      season,
      apiBase,
      publicKey,
      checkout,
      returnUrl,
      buyerAccessToken,
      initialOperationId,
      recoveryTimeoutMs,
      fetch,
      offer,
      maxSelection,
      numberOfPlacesToSelect,
      locale,
      initialView,
      enable3D,
      theme,
      className,
      style,
    } = props;
    const containerRef = useRef<HTMLDivElement | null>(null);
    const pickerRef = useRef<CoreSeasonPicker | null>(null);
    const latest = useRef(props);
    latest.current = props;
    const offerKey = JSON.stringify(offer ?? null);
    const themeKey = JSON.stringify(theme ?? null);

    useEffect(() => {
      const container = containerRef.current;
      if (!container) return;

      const { className: _className, style: _style, ...options } = latest.current;
      const picker = new CoreSeasonPicker({
        ...options,
        container,
        buyerAccessTokenProvider: options.buyerAccessTokenProvider
          ? (context) => latest.current.buyerAccessTokenProvider!(context)
          : undefined,
        onHold: (handoff) => latest.current.onHold?.(handoff),
        onHoldChange: (handoff) => latest.current.onHoldChange?.(handoff),
        onContinue: (handoff) => latest.current.onContinue?.(handoff),
        onRenewalIntent: (intent) => latest.current.onRenewalIntent?.(intent),
        onAccessExpired: (event) => latest.current.onAccessExpired?.(event),
        onAccessUnavailable: (event) => latest.current.onAccessUnavailable?.(event),
        onStatusChange: (event) => latest.current.onStatusChange?.(event),
        onError: (error) => latest.current.onError?.(error),
      });
      pickerRef.current = picker;
      void picker.render().catch(() => undefined);

      return () => {
        picker.destroy();
        if (pickerRef.current === picker) pickerRef.current = null;
      };
    }, [
      season, apiBase, publicKey, checkout, returnUrl,
      buyerAccessToken, initialOperationId, recoveryTimeoutMs, fetch,
      offerKey, maxSelection, numberOfPlacesToSelect, locale, initialView, enable3D, themeKey,
    ]);

    useImperativeHandle(ref, (): SeasonPickerHandle => ({
      holdSameSeat: (labels, operationId) => required(pickerRef).holdSameSeat(labels, operationId),
      restoreOperation: (operationId) => required(pickerRef).restoreOperation(operationId),
      release: (releaseActionId) => required(pickerRef).release(releaseActionId),
      createRenewalIntent: (offerId) => required(pickerRef).createRenewalIntent(offerId),
      getDescriptor: () => pickerRef.current?.getDescriptor() ?? null,
      getAvailability: () => pickerRef.current?.getAvailability() ?? null,
      getHandoff: () => pickerRef.current?.getHandoff() ?? null,
    }), []);

    return <div ref={containerRef} className={className} style={style} />;
  },
);

function required(ref: { current: CoreSeasonPicker | null }): CoreSeasonPicker {
  if (!ref.current) throw new Error('seatlayer: React SeasonPicker is not mounted');
  return ref.current;
}

// packages/angular/src/season-picker.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild,
  inject,
} from '@angular/core';
import {
  SeasonPicker as CoreSeasonPicker,
  type SeasonAvailability,
  type SeasonCheckoutHandoff,
  type SeasonDescriptor,
  type SeasonPickerOptions,
  type SeasonRenewalIntent,
  type SeasonStatusEvent,
} from '@seatlayer/js';

/** Standalone Angular adapter for the distinct fixed-inclusion Season buyer flow. */
@Component({
  selector: 'seatlayer-season-picker',
  standalone: true,
  template: '<div #container class="seatlayer-season-container"></div>',
  styles: [':host { display: block; } .seatlayer-season-container { width: 100%; }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SeatLayerSeasonPickerComponent implements OnChanges {
  /** Season key to render. */
  @Input({ required: true }) season!: string;

  /** Public API base override. */
  @Input() apiBase?: string;

  /** Refreshable one-time browser bearer provider. */
  @Input() buyerAccessTokenProvider?: SeasonPickerOptions['buyerAccessTokenProvider'];

  /** One-time Season browser bearer. */
  @Input() buyerAccessToken?: SeasonPickerOptions['buyerAccessToken'];

  /** Operation restored after an uncertain create response. */
  @Input() initialOperationId?: string;

  /** Maximum recovery polling time. */
  @Input() recoveryTimeoutMs?: number;

  /** Test or host fetch implementation. */
  @Input() fetch?: typeof fetch;

  /** A same-seat hold reached a safe handoff. */
  @Output() readonly hold = new EventEmitter<SeasonCheckoutHandoff>();

  /** The active handoff changed or was released. */
  @Output() readonly holdChange = new EventEmitter<SeasonCheckoutHandoff | null>();

  /** The buyer continued with an opaque handoff. */
  @Output() readonly continued = new EventEmitter<SeasonCheckoutHandoff>();

  /** A returning holder recorded browser intent only. */
  @Output() readonly renewalIntent = new EventEmitter<SeasonRenewalIntent>();

  /** Buyer access expired. */
  @Output() readonly accessExpired = new EventEmitter<unknown>();

  /** Buyer access cannot be recovered. */
  @Output() readonly accessUnavailable = new EventEmitter<unknown>();

  /** Buyer-visible operation status changed. */
  @Output() readonly statusChange = new EventEmitter<SeasonStatusEvent>();

  /** The Season buyer flow failed. */
  @Output() readonly errored = new EventEmitter<unknown>();

  @ViewChild('container', { static: true })
  private readonly container!: ElementRef<HTMLDivElement>;

  private static readonly REBUILD_INPUTS = new Set([
    'season', 'apiBase', 'buyerAccessTokenProvider', 'buyerAccessToken',
    'initialOperationId', 'recoveryTimeoutMs', 'fetch',
  ]);
  private readonly zone = inject(NgZone);
  private picker: CoreSeasonPicker | null = null;

  constructor() {
    inject(DestroyRef).onDestroy(() => this.destroy());
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (Object.keys(changes).some((name) => SeatLayerSeasonPickerComponent.REBUILD_INPUTS.has(name))) {
      this.build();
    }
  }

  /** Holds the same labels across every included occurrence. */
  holdSameSeat(labels: readonly string[], operationId: string): Promise<SeasonCheckoutHandoff> {
    return this.current().holdSameSeat(labels, operationId);
  }

  /** Restores a caller-stable Season operation after uncertainty. */
  restoreOperation(operationId: string): Promise<SeasonCheckoutHandoff | null> {
    return this.current().restoreOperation(operationId);
  }

  /** Releases the active selection with a caller-stable action id. */
  release(releaseActionId: string): Promise<void> {
    return this.current().release(releaseActionId);
  }

  /** Records renewal intent; trusted server code still inspects and commits it. */
  createRenewalIntent(offerId: string): Promise<SeasonRenewalIntent> {
    return this.current().createRenewalIntent(offerId);
  }

  /** Current immutable Season descriptor. */
  getDescriptor(): SeasonDescriptor | null {
    return this.picker?.getDescriptor() ?? null;
  }

  /** Current same-seat aggregate availability. */
  getAvailability(): SeasonAvailability | null {
    return this.picker?.getAvailability() ?? null;
  }

  /** Current opaque checkout handoff. */
  getHandoff(): SeasonCheckoutHandoff | null {
    return this.picker?.getHandoff() ?? null;
  }

  private build(): void {
    this.destroy();
    this.zone.runOutsideAngular(() => {
      const picker = new CoreSeasonPicker({
        container: this.container.nativeElement,
        season: this.season,
        apiBase: this.apiBase,
        buyerAccessTokenProvider: this.buyerAccessTokenProvider,
        buyerAccessToken: this.buyerAccessToken,
        initialOperationId: this.initialOperationId,
        recoveryTimeoutMs: this.recoveryTimeoutMs,
        fetch: this.fetch,
        onHold: (value) => this.zone.run(() => this.hold.emit(value)),
        onHoldChange: (value) => this.zone.run(() => this.holdChange.emit(value)),
        onContinue: (value) => this.zone.run(() => this.continued.emit(value)),
        onRenewalIntent: (value) => this.zone.run(() => this.renewalIntent.emit(value)),
        onAccessExpired: (value) => this.zone.run(() => this.accessExpired.emit(value)),
        onAccessUnavailable: (value) => this.zone.run(() => this.accessUnavailable.emit(value)),
        onStatusChange: (value) => this.zone.run(() => this.statusChange.emit(value)),
        onError: (value) => this.zone.run(() => this.errored.emit(value)),
      });
      this.picker = picker;
      void picker.render().catch(() => undefined);
    });
  }

  private current(): CoreSeasonPicker {
    if (!this.picker) throw new Error('seatlayer: Angular SeasonPicker is not mounted');
    return this.picker;
  }

  private destroy(): void {
    this.picker?.destroy();
    this.picker = null;
  }
}
