// packages/react/src/SeatingChart.tsx
import {
  forwardRef,
  useEffect,
  useImperativeHandle,
  useRef,
  type CSSProperties,
} from 'react';
import {
  SeatingChart as CoreSeatingChart,
  type SeatingChartOptions,
  type SelectedSeat,
  type HoldResult,
  type BestAvailableResult,
  type GAAreaAvailability,
  type HoldLineItem,
} from '@seatlayer/js';

export type { SelectedSeat, HoldResult, BestAvailableResult, GAAreaAvailability, HoldLineItem } from '@seatlayer/js';
export type { SeatHoverDetails } from '@seatlayer/js';

/** Imperative handle exposed via `ref` — call these to drive the picker from your app. */
export interface SeatingChartHandle {
  /** Hold the current selection. Resolves the hold, or `null` on a 409 conflict. */
  hold(options?: { ttlMs?: number }): Promise<HoldResult | null>;
  /** Restore an active hold by its opaque id. */
  resumeHold(holdId: string): Promise<HoldResult | null>;
  /** Current active hold known to the chart. */
  getCurrentHold(): HoldResult | null;
  /** GA areas with live remaining capacity. */
  getGAAreas(): GAAreaAvailability[];
  /** Atomically hold a quantity from one GA area. */
  holdGA(areaId: string, qty: number, options?: { tierId?: string | null; ttlMs?: number }): Promise<HoldResult | null>;
  /** Ask the server for the `qty` best free seats and hold them atomically. */
  bestAvailable(qty: number, categoryKey?: string): Promise<BestAvailableResult | null>;
  /** Release the current hold (if any). */
  release(): Promise<void>;
  /** Release some held labels while keeping the remainder active. */
  releaseLabels(labels: string[]): Promise<boolean>;
  /** The current selection, with prices resolved from the chart categories. */
  getSelection(): SelectedSeat[];
  /**
   * Choose a ticket tier for a selected seat (e.g. Adult → Child). Available
   * `tiers` are on each `SelectedSeat`; `tierId=null` reverts to the default.
   */
  setSeatTier(seatId: string, tierId: string | null): void;
  /**
   * Floors of a multi-floor chart — `[{ id, name }]` (single-floor charts
   * return one entry; empty before render()). Pair with setFloor().
   */
  getFloors(): { id: string; name: string }[];
  /** Switch the shown floor (2D). Warns + no-ops on single-floor charts. */
  setFloor(floorId: string): void;
  /** Toggle colorblind-safe rendering at runtime (see the `colorblindSafe` prop). */
  setColorblindSafe(on: boolean): void;
  /** Zoom in one step (same increment as the wheel/pinch gesture). */
  zoomIn(): void;
  /** Zoom out one step. */
  zoomOut(): void;
  /** Reset the camera so the whole chart fits the container. */
  zoomToFit(): void;
  /**
   * Re-acquire the buyer access session after your app re-authorizes the buyer
   * (Sales Channels). Resolves false when the chart is not access-scoped.
   */
  refreshAccess(): Promise<boolean>;
}

export interface SeatingChartProps extends Omit<SeatingChartOptions, 'container'> {
  className?: string;
  style?: CSSProperties;
}

/**
 * React wrapper around the framework-agnostic `@seatlayer/js` SDK.
 *
 * The underlying canvas is created once and torn down on unmount. Callback props
 * (`onSelectionChange`, `onHold`, `onError`, `onDeckTap`, `onHint`) may change
 * freely between renders without re-mounting the canvas — only `event`,
 * `apiBase`, `maxSelection`, `publicKey`, `locale`, `currency`, and
 * `colorblindSafe` trigger a rebuild. (`messages` is read once per mount;
 * changing it alone does not re-apply.)
 */
export const SeatingChart = forwardRef<SeatingChartHandle, SeatingChartProps>(
  function SeatingChart(props, ref) {
    const { className, style, event, apiBase, maxSelection, publicKey, locale, currency, colorblindSafe } = props;

    const containerRef = useRef<HTMLDivElement | null>(null);
    const chartRef = useRef<CoreSeatingChart | null>(null);

    // Always call the latest callbacks without rebuilding the chart.
    const callbacks = useRef(props);
    callbacks.current = props;

    useEffect(() => {
      const el = containerRef.current;
      if (!el) return;

      const chart = new CoreSeatingChart({
        container: el,
        event,
        apiBase,
        maxSelection,
        publicKey,
        locale,
        currency,
        colorblindSafe,
        messages: callbacks.current.messages,
        // Read through the ref so a host may pass the provider as an inline
        // arrow without its new identity tearing the canvas down each render.
        buyerAccessTokenProvider: props.buyerAccessTokenProvider
          ? (context) => callbacks.current.buyerAccessTokenProvider!(context)
          : undefined,
        buyerAccessToken: callbacks.current.buyerAccessToken,
        onAccessExpired: (state) => callbacks.current.onAccessExpired?.(state),
        onAccessUnavailable: (state) => callbacks.current.onAccessUnavailable?.(state),
        onSelectedObjectUnavailable: (state) =>
          callbacks.current.onSelectedObjectUnavailable?.(state),
        onSelectionChange: (seats) => callbacks.current.onSelectionChange?.(seats),
        onHold: (result) => callbacks.current.onHold?.(result),
        onHoldRestored: (result) => callbacks.current.onHoldRestored?.(result),
        onHoldExpired: () => callbacks.current.onHoldExpired?.(),
        onGAClick: (area) => callbacks.current.onGAClick?.(area),
        onError: (err) => callbacks.current.onError?.(err),
        onDeckTap: (floorId) => callbacks.current.onDeckTap?.(floorId),
        onHint: (message) => callbacks.current.onHint?.(message),
        seatTooltip: props.seatTooltip,
        onSeatHover: (details) => callbacks.current.onSeatHover?.(details),
      });
      chartRef.current = chart;
      void chart.render();

      return () => {
        chart.destroy();
        chartRef.current = null;
      };
      // Rebuild only when the identity of the chart changes.
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [event, apiBase, maxSelection, publicKey, locale, currency, colorblindSafe]);

    useImperativeHandle(
      ref,
      (): SeatingChartHandle => ({
        hold: (options) => chartRef.current?.hold(options) ?? Promise.resolve(null),
        resumeHold: (holdId) => chartRef.current?.resumeHold(holdId) ?? Promise.resolve(null),
        getCurrentHold: () => chartRef.current?.getCurrentHold() ?? null,
        getGAAreas: () => chartRef.current?.getGAAreas() ?? [],
        holdGA: (areaId, qty, options) => chartRef.current?.holdGA(areaId, qty, options) ?? Promise.resolve(null),
        bestAvailable: (qty, categoryKey) =>
          chartRef.current?.bestAvailable(qty, categoryKey) ?? Promise.resolve(null),
        release: () => chartRef.current?.release() ?? Promise.resolve(),
        releaseLabels: (labels) => chartRef.current?.releaseLabels(labels) ?? Promise.resolve(false),
        getSelection: () => chartRef.current?.getSelection() ?? [],
        setSeatTier: (seatId, tierId) => chartRef.current?.setSeatTier(seatId, tierId),
        getFloors: () => chartRef.current?.getFloors() ?? [],
        setFloor: (floorId) => chartRef.current?.setFloor(floorId),
        setColorblindSafe: (on) => chartRef.current?.setColorblindSafe(on),
        zoomIn: () => chartRef.current?.zoomIn(),
        zoomOut: () => chartRef.current?.zoomOut(),
        zoomToFit: () => chartRef.current?.zoomToFit(),
        refreshAccess: () => chartRef.current?.refreshAccess() ?? Promise.resolve(false),
      }),
      [],
    );

    return <div ref={containerRef} className={className} style={style} />;
  },
);

// packages/angular/src/seating-chart.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  EventEmitter,
  Input,
  NgZone,
  OnChanges,
  Output,
  SimpleChanges,
  ViewChild,
  inject,
} from '@angular/core';
import {
  SeatingChart as CoreSeatingChart,
  type SeatingChartOptions,
  type SelectedSeat,
  type HoldResult,
  type BestAvailableResult,
  type GAAreaAvailability,
  type SeatHoverDetails,
} from '@seatlayer/js';

/**
 * Angular wrapper around the framework-agnostic `@seatlayer/js` SDK.
 *
 * Standalone, so it is imported directly rather than through an NgModule.
 *
 * The canvas is created once and torn down on destroy. Only the inputs that
 * change the chart's identity — `event`, `apiBase`, `maxSelection`, `publicKey`,
 * `locale`, `currency`, `colorblindSafe` — trigger a rebuild, so an unrelated
 * change-detection pass never destroys the canvas mid-selection.
 *
 * @example
 * ```html
 * <seatlayer-seating-chart
 *   #chart
 *   event="summer-gala"
 *   (selectionChange)="onSelectionChange($event)"
 *   (hold)="onHold($event)"
 * />
 * <button (click)="chart.hold()">Continue</button>
 * ```
 */
@Component({
  selector: 'seatlayer-seating-chart',
  standalone: true,
  template: '<div #container class="seatlayer-container"></div>',
  styles: [':host { display: block; } .seatlayer-container { width: 100%; height: 100%; }'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SeatLayerSeatingChartComponent implements OnChanges {
  /** Event key to render. Changing it rebuilds the chart. */
  @Input({ required: true }) event!: string;

  /** API base URL. Defaults to the public API. */
  @Input() apiBase?: string;

  /** Cap on how many seats a buyer may select. */
  @Input() maxSelection?: number;

  /** Publishable key, when your integration uses one. */
  @Input() publicKey?: string;

  /** BCP-47 locale for built-in copy. */
  @Input() locale?: string;

  /** ISO currency for price formatting. */
  @Input() currency?: string;

  /** Render with colorblind-safe seat glyphs. */
  @Input() colorblindSafe?: boolean;

  /** Show the built-in seat tooltip. Set false to draw your own from `seatHover`. */
  @Input() seatTooltip?: boolean;

  /** Copy overrides, read once per rebuild. */
  @Input() messages?: SeatingChartOptions['messages'];

  /** The buyer's selection changed. */
  @Output() readonly selectionChange: EventEmitter<SelectedSeat[]> = new EventEmitter<SelectedSeat[]>();

  /** A hold succeeded. */
  @Output() readonly hold: EventEmitter<HoldResult> = new EventEmitter<HoldResult>();

  /** A previous hold was restored on mount. */
  @Output() readonly holdRestored: EventEmitter<HoldResult> = new EventEmitter<HoldResult>();

  /** The active hold lapsed. */
  @Output() readonly holdExpired: EventEmitter<void> = new EventEmitter<void>();

  /** A GA area was clicked. */
  @Output() readonly gaClick: EventEmitter<GAAreaAvailability> = new EventEmitter<GAAreaAvailability>();

  /** Something failed — a network error, a rejected hold. */
  @Output() readonly errored: EventEmitter<unknown> = new EventEmitter<unknown>();

  /** A floor deck was tapped in the 3D view. */
  @Output() readonly deckTap: EventEmitter<string> = new EventEmitter<string>();

  /** A transient hint worth showing the buyer, or `null` to clear it. */
  @Output() readonly hint: EventEmitter<string | null> = new EventEmitter<string | null>();

  /** The pointer moved onto a seat, or off one (`null`). */
  @Output() readonly seatHover: EventEmitter<SeatHoverDetails | null> = new EventEmitter<SeatHoverDetails | null>();

  @ViewChild('container', { static: true })
  private readonly container!: ElementRef<HTMLDivElement>;

  private readonly zone = inject(NgZone);
  private chart: CoreSeatingChart | null = null;

  /** Inputs that require tearing the canvas down and rebuilding it. */
  private static readonly REBUILD_INPUTS = [
    'event', 'apiBase', 'maxSelection', 'publicKey', 'locale', 'currency', 'colorblindSafe',
  ] as const;

  constructor() {
    inject(DestroyRef).onDestroy(() => this.destroy());
  }

  ngOnChanges(changes: SimpleChanges): void {
    const needsRebuild = SeatLayerSeatingChartComponent.REBUILD_INPUTS.some((name) => name in changes);
    if (needsRebuild) {
      this.build();
    }
  }

  // ---------- imperative API, for a template ref ----------

  /** Hold the current selection. Resolves the hold, or `null` on a 409 conflict. */
  holdSelection(options?: { ttlMs?: number }): Promise<HoldResult | null> {
    return this.chart?.hold(options) ?? Promise.resolve(null);
  }

  /** Restore an active hold by its opaque id. */
  resumeHold(holdId: string): Promise<HoldResult | null> {
    return this.chart?.resumeHold(holdId) ?? Promise.resolve(null);
  }

  /** Current active hold known to the chart. */
  getCurrentHold(): HoldResult | null {
    return this.chart?.getCurrentHold() ?? null;
  }

  /** GA areas with live remaining capacity. */
  getGAAreas(): GAAreaAvailability[] {
    return this.chart?.getGAAreas() ?? [];
  }

  /** Atomically hold a quantity from one GA area. */
  holdGA(
    areaId: string,
    qty: number,
    options?: { tierId?: string | null; ttlMs?: number },
  ): Promise<HoldResult | null> {
    return this.chart?.holdGA(areaId, qty, options) ?? Promise.resolve(null);
  }

  /** Ask the server for the `qty` best free seats and hold them atomically. */
  bestAvailable(qty: number, categoryKey?: string): Promise<BestAvailableResult | null> {
    return this.chart?.bestAvailable(qty, categoryKey) ?? Promise.resolve(null);
  }

  /** Release the current hold (if any). */
  release(): Promise<void> {
    return this.chart?.release() ?? Promise.resolve();
  }

  /** Release some held labels while keeping the remainder active. */
  releaseLabels(labels: string[]): Promise<boolean> {
    return this.chart?.releaseLabels(labels) ?? Promise.resolve(false);
  }

  /** The current selection, with prices resolved from the chart categories. */
  getSelection(): SelectedSeat[] {
    return this.chart?.getSelection() ?? [];
  }

  /** Choose a ticket tier for a selected seat; `null` reverts to the default. */
  setSeatTier(seatId: string, tierId: string | null): void {
    this.chart?.setSeatTier(seatId, tierId);
  }

  /** Floors of a multi-floor chart. Empty before the first render. */
  getFloors(): { id: string; name: string }[] {
    return this.chart?.getFloors() ?? [];
  }

  /** Switch the shown floor (2D). No-ops on single-floor charts. */
  setFloor(floorId: string): void {
    this.chart?.setFloor(floorId);
  }

  /** Toggle colorblind-safe rendering at runtime. */
  setColorblindSafe(on: boolean): void {
    this.chart?.setColorblindSafe(on);
  }

  /** Zoom in one step (same increment as the wheel/pinch gesture). */
  zoomIn(): void {
    this.chart?.zoomIn();
  }

  /** Zoom out one step. */
  zoomOut(): void {
    this.chart?.zoomOut();
  }

  /** Reset the camera so the whole chart fits the container. */
  zoomToFit(): void {
    this.chart?.zoomToFit();
  }

  // ---------- internals ----------

  private build(): void {
    const element = this.container?.nativeElement;
    if (!element) return;

    this.destroy();

    // The chart runs a rAF render loop and pointer handlers. Left inside the
    // Angular zone, every frame would schedule change detection for the whole
    // application — so it is built outside, and each callback re-enters the zone
    // only to emit, which is the only part Angular needs to see.
    this.zone.runOutsideAngular(() => {
      const emit = <T>(emitter: EventEmitter<T>, value: T) =>
        this.zone.run(() => emitter.emit(value));

      const instance = new CoreSeatingChart({
        container: element,
        event: this.event,
        apiBase: this.apiBase,
        maxSelection: this.maxSelection,
        publicKey: this.publicKey,
        locale: this.locale,
        currency: this.currency,
        colorblindSafe: this.colorblindSafe,
        seatTooltip: this.seatTooltip,
        messages: this.messages,
        onSelectionChange: (seats) => emit(this.selectionChange, seats),
        onHold: (result) => emit(this.hold, result),
        onHoldRestored: (result) => emit(this.holdRestored, result),
        onHoldExpired: () => this.zone.run(() => this.holdExpired.emit()),
        onGAClick: (area) => emit(this.gaClick, area),
        onError: (error) => emit(this.errored, error),
        onDeckTap: (floorId) => emit(this.deckTap, floorId),
        onHint: (message) => emit(this.hint, message),
        onSeatHover: (details) => emit(this.seatHover, details),
      });

      this.chart = instance;
      void instance.render();
    });
  }

  private destroy(): void {
    this.chart?.destroy();
    this.chart = null;
  }
}
